# Pre-commit configuration for kicad-svg-extras
repos:
  - repo: local
    hooks:
      - id: lint-all
        name: Run linting and type checks
        entry: hatch run lint:all
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-toml
