name: CI

on:
  push:
  pull_request:
    branches: [ "master", "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install KiCad
      run: |
        sudo add-apt-repository --yes ppa:kicad/kicad-9.0-releases
        sudo apt update
        sudo apt install --install-recommends kicad

    - name: Verify KiCad installation
      run: kicad-cli version

    - name: Install test dependencies
      run: |
        pip install --upgrade -r dev-requirements.txt
        pip install -e .

    - name: Run tests
      run: pytest --cov kicad_svg_extras tests/

    - name: Coverage
      run: |
        echo '### coverage' >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        coverage report -m >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Hatch
      run: pip install --upgrade hatch

    - name: Run linting
      run: hatch run lint:all

  check-build:
    name: Check package build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Hatch
      run: pip install --upgrade hatch

    - name: Build package
      run: hatch build

    - name: Check package
      run: |
        pip install twine
        twine check dist/*

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
